version: "3.5"

services:
  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./order-api
    env_file:
      - .env.dev
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      RUBYOPT: '-W0'
    volumes:
      - ./order-api/:/root
      - gems:/usr/local/bundle
    ports:
      - 3000:3000
    command: bash -c "./bin/dev_setup && rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - postgres

  ui:
    build: ./order-ui
    environment:
      NODE_ENV: development
    volumes:
      - ./order-ui/:/root
    ports:
      - 4200:4200
    depends_on:
      - app
    command: bash -c "yarn install && ng serve --host 0.0.0.0"

volumes:
  db_data:
  gems:
